language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_182d1a38c631_key -iv $encrypted_182d1a38c631_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- gradle wrapper
addons:
  sonarcloud:
    organization: ylinor-github
script:
- "./gradlew sonarqube"
- "./gradlew build"
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/libs/* aventurier@onaple.fr:~/sponge-server-1.12/mods/
  on:
    all_branches: true
