language: java
jdk:
- oraclejdk8
before_install:
- gradle wrapper
addons:
  sonarcloud:
    organization: ylinor-github
  ssh_known_hosts: onaple.fr
script:
- "./gradlew sonarqube"
before_deploy:
- openssl aes-256-cbc -K $encrypted_0d7303d7684b_key -iv $encrypted_0d7303d7684b_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    tags: true
    all_branches: false
