language: java
jdk:
- oraclejdk8
before_install:
- gradle wrapper
addons:
  sonarcloud:
    organization: ylinor-github
script:
- "./gradlew sonarqube"
- "./gradlew build"
before_deploy:
- openssl aes-256-cbc -K $encrypted_28b7acc5ef9b_key -iv $encrypted_28b7acc5ef9b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/lib/* aventurier@onaple.fr:~/sponge-server-1.12/mods/
  on:
    all_branches: true
